### ISSUE TITLE
Capacitor 6

### ISSUE THREAD

**Issue by Majstr** [BlinkID/blinkid-capacitor#36]
Please add support for Capacitor 6 in next release.

**Comment by mparadina** [comment]
Hi @Majstr 

The next release of BlinkID, 6.7.0, is scheduled to be released by the end of next week, so we will not be adding support for Capacitor v6 in this release.
However, we can plan it on our roadmap to add it to the 6.8.0 version.

**Comment by Majstr** [comment]
That would be great. We want to use your new DirectApi, but we have Capacitor 6.

**Comment by mparadina** [comment]
Of course, I can update you here once the 6.8.0 version has been released.
In the meantime, let me know if there is anything else I can assist you with.

**Comment by Majstr** [comment]
Do you have any news about next release? I saw version 6.7.0 is out.

**Comment by mparadina** [comment]
@Majstr hello! We've released BlinkID Capacitor [v6.9.0](https://github.com/BlinkID/blinkid-capacitor/releases/tag/v6.9.0), which contains the support for Capacitor v6.

Can you test it out and let me know if it works as expected?

**Comment by Majstr** [comment]
@mparadina Hi. We tested it and it doesn't work as expected. Problem is with direct SDK. First scan works than it goes to same error state and we can't scan anymore. We already send you mail with all the data.
