### ISSUE TITLE
Cant resolve '@capacitor/core'

### ISSUE THREAD

**Issue by WeiChun0723** [BlinkID/blinkid-capacitor#6]
When I install in my ionic project and start compiling get this error 
![Uploading image.png…]()

**Comment by SandraKuzmic** [comment]
Hi @WeiChun0723 

I can't preview the image with the error, can you please send it again? 

Also, when does the error occur? Are you getting this error after running our [init script](https://github.com/BlinkID/blinkid-capacitor/blob/master/initIonicSampleApp.sh) or did you manually add BlinkID plugin in your project?

Best regards,
Sandra

**Comment by WeiChun0723** [comment]
Hi @SandraKuzmic ,

Looks like we missing some step when installing the plugin , it works fine after follow every steps. Will close the issue.
